
PAGE_CONFIG = {"page_title"            : "Precio coches segunda mano",
               "page_icon"             : ":oncoming_automobile:",
               "layout"                : "centered",
               "initial_sidebar_state" : "collapsed"}

combustibles= ["Diésel", 
               "Gasolina", 
               "Híbrido",
               "Eléctrico", 
               "Híbrido Enchufable", 
               "Gas"]

provincias = ["Álava", 
              "Albacete", 
              "Alicante", 
              "Almería", 
              "Asturias", 
              "Ávila",
              "Badajoz", 
              "Barcelona", 
              "Burgos", 
              "Cáceres", 
              "Cádiz", 
              "Cantabria",
              "Castellón", 
              "Ceuta", 
              "Ciudad Real", 
              "Córdoba", 
              "Cuenca", 
              "Girona",
              "Granada", 
              "Guadalajara", 
              "Guipúzcoa", 
              "Huelva", 
              "Huesca", 
              "Islas Baleares", 
              "Jaén", 
              "La Coruña", 
              "La Rioja", 
              "Las Palmas",
              "León", 
              "Lleida", 
              "Lugo", 
              "Madrid", 
              "Málaga",  
              "Murcia",
              "Navarra", 
              "Orense", 
              "Palencia", 
              "Pontevedra", 
              "Salamanca", 
              "Segovia", 
              "Sevilla", 
              "Soria", 
              "Tenerife", 
              "Tarragona", 
              "Teruel",
              "Toledo", 
              "Valencia", 
              "Valladolid", 
              "Vizcaya", 
              "Zamora", 
              "Zaragoza"]

marcas = ['ABARTH', 
          'AIWAYS', 
          'ALFA', 
          'ALPINE', 
          'ASTON', 
          'AUDI', 
          'BENTLEY', 
          'BMW', 
          'CADILLAC', 
          'CHEVROLET', 
          'CHRYSLER', 
          'CITROEN', 
          'CORVETTE', 
          'CUPRA', 
          'DACIA', 
          'DAEWOO', 
          'DAIMLER', 
          'DFSK', 
          'DODGE', 
          'DR', 
          'DS', 
          'FERRARI', 
          'FIAT', 
          'FORD', 
          'GALLOPER', 
          'GMC', 
          'HONDA', 
          'HUMMER', 
          'HURTAN', 
          'HYUNDAI', 
          'INFINITI', 
          'ISUZU', 
          'JAGUAR', 
          'JEEP', 
          'KARMA', 
          'KIA', 
          'LAMBORGHINI', 
          'LANCIA', 
          'LAND-ROVER', 
          'LEVC', 
          'LEXUS', 
          'LINCOLN', 
          'LOTUS', 
          'LYNK', 
          'MASERATI', 
          'MAHINDRA', 
          'MAXUS', 
          'MAZDA', 
          'MERCEDES-BENZ', 
          'MG', 
          'MINI', 
          'MITSUBISHI', 
          'MORGAN', 
          'NISSAN', 
          'OPEL', 
          'PEUGEOT', 
          'POLESTAR', 
          'PONTIAC', 
          'PORSCHE', 
          'RENAULT', 
          'ROVER', 
          'ROLLS-ROYCE', 
          'SAAB', 
          'SANTANA', 
          'SEAT', 
          'SKODA', 
          'SMART', 
          'SSANGYONG', 
          'SUBARU', 
          'SUZUKI', 
          'SWM', 
          'TATA', 
          'TESLA', 
          'TOYOTA', 
          'VOLKSWAGEN', 
          'VOLVO', 
          'WIESMANN']

